---
resources:
- name: resource
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
- name: hazelResource
  type: git
  source:
    uri: https://github.com/hazelcedar/concourceTutorial.git
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource
  - task: hello-world
    file: resource/tutorials/basic/task-hello-world/task_hello_world.yml

